# Generated by Django 3.1.7 on 2021-04-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('card_type', models.CharField(choices=[('CC', 'Credit card'), ('DC', 'Debit card')], default='CR', max_length=2)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('income_type', models.CharField(choices=[('DB', 'Debt'), ('RD', 'Recurring debt'), ('CD', 'Card debt'), ('SM', 'Separate money'), ('RI', 'Recurring income'), ('AI', 'Additional income')], default='DV', max_length=3)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=650)),
                ('init_date', models.DateField()),
                ('final_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('goal', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
