# Generated by Django 3.1.7 on 2021-03-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('card_type', models.CharField(choices=[('CR', 'Crédito'), ('DE', 'Débito')], default='CR', max_length=2)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('DV', 'Dívida'), ('DVR', 'Dívida recorrentes'), ('DVC', 'Dívida com cartão'), ('DS', 'Dinheiro separado'), ('RR', 'Renda recorrente'), ('RA', 'Renda adicional')], default='DV', max_length=3)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goal', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
