# Generated by Django 3.1.7 on 2021-03-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='credit',
        ),
        migrations.AlterField(
            model_name='card',
            name='limit',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='financeincome',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='savings',
            name='goal',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='savings',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
