# Generated by Django 3.1.7 on 2021-03-30 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_auto_20210330_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
