# Generated by Django 3.1.7 on 2021-04-03 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0002_planning_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='user',
        ),
        migrations.AddField(
            model_name='planning',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
