# Generated by Django 3.1.7 on 2021-03-30 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_savings_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financeincome',
            old_name='nome',
            new_name='name',
        ),
    ]
