# Generated by Django 3.1.7 on 2021-04-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_planning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financeincome',
            old_name='valor',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='savings',
            old_name='valor',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='financeincome',
            name='tipo',
        ),
        migrations.AddField(
            model_name='financeincome',
            name='income_type',
            field=models.CharField(choices=[('DB', 'Debt'), ('RD', 'Recurring debt'), ('CD', 'Card debt'), ('SM', 'Separate money'), ('RI', 'Recurring income'), ('AI', 'Additional income')], default='DV', max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('CC', 'Credit card'), ('DC', 'Debit card')], default='CR', max_length=2),
        ),
    ]
